name: release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: '. -> target'

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: '18.17.0'
          cache: 'yarn'

      - name: Install frontend dependencies
        run: yarn install

      - name: Create secrets (Rust)
        uses: 1arp/create-a-file-action@0.4.4
        with:
          path: 'src/utils'
          file: 'secrets.rs'
          content: ${{ secrets.RUST_SECRET }}

      - name: Create secrets (Typescript)
        uses: 1arp/create-a-file-action@0.4.4
        with:
          path: 'webapp/src/utils'
          file: 'secrets.ts'
          content: ${{ secrets.WEBAPP_SECRET }}

      - name: Build the app
        uses: tauri-apps/tauri-action@v0

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: 'Open Streamer Companion v__VERSION__'
          releaseBody: 'See the assets to download and install this version.'
          releaseDraft: true
          prerelease: false